apiVersion: v1
kind: Secret
metadata:
  name: casino-secret
type: Opaque
data:
  # Thay thế các chuỗi dưới đây bằng mã Base64 thực tế của bạn
  db-password: ${DB_PASSWORD_BASE64}
  mail-password: ${MAIL_PASSWORD_BASE64}